### ISSUE TITLE
Reorder colors (light theme)

### ISSUE THREAD

**Issue by michael-franke** [CogSciPrag/cspplot#3]
After some real-life plotting, it seems to me that the first two colors of the light theme are not different enough under many common use cases (alpha < 1, thin lines or points ...).
I would suggest to reorder by moving what is now the 2nd color to what is now position 5. In code:

new_list = cspplot::list_colors()[c(1,3,4,5,2,6:14),]

**Comment by julianeschwab** [comment]
I have reordered the colors accordingly. I agree that this looks better!
